# Generated by Django 5.2.8 on 2025-12-02 12:33

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viewflow', '0014_alter_process_parent_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('viewflow.process',),
        ),
    ]
